/**
 * @description       : Clase de prueba CT_Reporte_Horas_Fact_Controller
 * @author            : marcohernandezhp@gmail.com
 * @group             : 
 * @last modified on  : 02-14-2023
 * @last modified by  : marcohernandezhp@gmail.com
**/
@isTest
public without sharing class CT_Reporte_Horas_Fact_Controller_Test {
    @IsTest
    static void methodName(){
        CT_Reporte_Horas_Fact_Controller rhfCtrl = new CT_Reporte_Horas_Fact_Controller();
        CT_Reporte_Horas_Fact_Controller.getConfig();
        
    }
}