public class QuoteSoftlandPayload {
    public String compania;
    //public String sucursal;
    public String taller;
    public String total_mercaderia;
    public String total_impuesto2;
    public String total_impuesto1;
    public String total_a_facturar;
    public String request_id;
    public String porc_descuento2;
    public String porc_descuento1;
    public String oportunidad;
    public String monto_descuento2;
    public String monto_descuento1;
    public String moneda;
    public String cod_cliente;
    
    public String aseguradoraPedido;
    
    public String descripcion;
    
    public String vin;
    public String placa;
    
    public String cargo;
    
    public String nombreFacturacion;
    public String correoFacturacion;
    public String telefonoFacturacion;
    public String codigoSoftlandFacturacion;
    
    public List<QuoteLine> lineas;

    public class QuoteLine {
        public String centro_costo;
        public String total_mercaderia;
        public String total_impuesto;
        public String total_descuento;
        public String total_a_facturar;
        public String precio_unitario;
        public String porc_descuento;
        public String monto_descuento;
        public String id_linea;
        public String desc_articulo;
        public String comentario;
        public String cod_articulo;
        public String cantidad;
    }

    public static void Method() {
        Integer a = 1;
        Integer b = 2;
        Integer c = 3;
        Integer d = 4;
        Integer e = 5;
        Integer f = 6;
        Integer g = 7;
        Integer h = 8;
        Integer i = 9;
        Integer j = 10;
        Integer k = 11;
        Integer l = 12;
        Integer m = 13;
        Integer n = 14;
        Integer o = 15;
        Integer p = 16;
        Integer q = 17;
        Integer r = 18;
        Integer s = 19;
        Integer t = 20;
        Integer u = 21;
        Integer v = 22;
        Integer w = 23;
        Integer x = 24;
        Integer y = 25;
        Integer z = 26;
        Integer aa = 27;
        Integer bb = 28;
        Integer cc = 29;
        Integer dd = 30;
        Integer ee = 31;
        Integer ff = 32;
        Integer gg = 33;
        Integer hh = 34;
        Integer ii = 35;
        Integer jj = 36;
        Integer kk = 37;
        Integer ll = 38;
        Integer mm = 39;
        Integer nn = 40;
        Integer oo = 41;
        Integer pp = 42;
        Integer qq = 43;
        Integer rr = 44;
        Integer ss = 45;
        Integer tt = 46;
        Integer uu = 47;
        Integer vv = 48;
        Integer ww = 49;
        Integer xx = 50;
        Integer yy = 51;
        Integer zz = 52;
        Integer aaa = 53;
        Integer bbb = 54;
        Integer ccc = 55;
        }
        
}