/**
 * @description       : 
 * @author            : marcohernandezhp@gmail.com
 * @group             : Redmotors
 * @last modified on  : 08-30-2023
 * @last modified by  : marcohernandezhp@gmail.com
**/
@IsTest
public with sharing class RM_Lead_Trigger_Helper_Test {
    @IsTest
    static void methodName(){
        
        RM_Lead_Trigger_Helper lth = new RM_Lead_Trigger_Helper();
        lth.name();
        
    }
}