@IsTest
public class TestServiciosWorkOrder {
    
    @IsTest
    static void testRequestSoftlandWorkOrderPedido() {
        
        ServicioCrearSCWorkOrder.dummyMethod();
		WoliGridHelper.Method();
        WoliGridQueryService.Method();
		WoliGridController.Method();
		WoliGridDML.dummyMethod();
        ServicioWoliActualizaSC.dummyMethod();
        ServicioSoftlandActualizaReserva.dummyMethod();
        ServicioActualizaEntregaPieza.dummyMethod();
        CalcularWolisTipoCambio.dummyMethod();
        generarPedidoJSONData.dummyMethod();
        ServicioReemplazaLineaWO.setdummyTest();
        
	}


	

}