/**
 * @description       : 
 * @author            : Marco Hernandez
 * @group             : Redmotors
 * @last modified on  : 09-02-2022
 * @last modified by  : marcohernandezhp@gmail.com
**/
@isTest
public class WorkStepWrapperTest {
    @IsTest
    static void getCreateWorkStepWrapper(){        
        WorkStepWrapper newWorkStepWrapper = new  WorkStepWrapper(null);

        // System.assert(WorkStepWrapper.getChildColor('') == '')
    }
}